# Generated by Django 6.0.7 on 2026-08-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parent_task',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Hạn chót hoàn thành', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_pomodoros',
            field=models.PositiveIntegerField(default=1, help_text='Số lượng phiên Pomodoro dự kiến'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2, help_text='1: Low, 2: Medium, 3: High'),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder',
            field=models.DateTimeField(blank=True, help_text='Thời điểm gửi thông báo nhắc nhở', null=True),
        ),
    ]
