# Generated by Django 6.0.7 on 2026-08-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_remove_task_parent_task_task_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_pomodoros',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='focus_duration',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='short_break',
            field=models.IntegerField(default=5),
        ),
    ]
