# Generated by Django 6.0.7 on 2026-08-03 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_task_deadline_alter_task_estimated_pomodoros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
