# Generated by Django 6.0.7 on 2026-08-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_remove_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_pomodoros',
            field=models.IntegerField(default=0),
        ),
    ]
