# Generated by Django 6.0.7 on 2026-08-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_pomodorosession'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
