# Generated by Django 6.0.7 on 2026-08-23 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_pomodoros',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='focus_duration',
            field=models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='short_break',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
