# Generated by Django 6.0.7 on 2026-08-02 15:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_preferred_background_sound_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXXztlgqVSoGrWtLaV90aqRd230C_XSxPInEGm3wh3GuUmw48rfMBWvQCn&s=10', max_length=255, verbose_name='avatar'),
        ),
    ]
