# Generated by Django 6.0.7 on 2026-08-26 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_storeitem_useritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritem',
            name='is_equipped',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_animation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_animation_users', to='gamification.storeitem'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_sound_users', to='gamification.storeitem'),
        ),
    ]
